// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/addon/mysql5/cluster/create": {
            "post": {
                "description": "创建MySQL V5集群",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "add-on"
                ],
                "summary": "创建MySQL V5集群",
                "parameters": [
                    {
                        "description": "创建 MySQL V5集群所需参数.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mysql5.ClusterOptions"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/addon/mysql5/operator": {
            "post": {
                "description": "在Kubernetes集群中安装 MySQL V5 Operator.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "add-on"
                ],
                "summary": "在Kubernetes集群中安装 MySQL V5 Operator.",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "从Kubernetes集群中删除MySQL V5 Operator.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "add-on"
                ],
                "summary": "从Kubernetes集群中删除MySQL V5 Operator.",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/configmap/create": {
            "post": {
                "description": "创建 ConfigMap 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "创建 ConfigMap 对象",
                "parameters": [
                    {
                        "description": "创建 ConfigMap 对象时所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/configmap.CreateConfigMapRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/configmap/delete": {
            "delete": {
                "description": "删除指定 ConfigMap 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定 ConfigMap 对象",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/configmap.DeleteConfigMapRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/configmap/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一 ConfigMap 对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 ConfigMap 对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ConfigMap 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/configmap/list/{namespace}": {
            "get": {
                "description": "获取某一命名空间下的所有 ConfigMap 对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一命名空间下的所有 ConfigMap 对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/container/logs/{namespace}/{podId}/{containerId}": {
            "get": {
                "description": "获取某一 Container 对象的 Logs.",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一 Container 对象的 Logs.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PodID",
                        "name": "podId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Container",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/cronjob/create": {
            "post": {
                "description": "创建 CronJob 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "创建 CronJob 对象",
                "parameters": [
                    {
                        "description": "创建 CronJob 对象所需参数.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cronjob.CreateCronJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/cronjob/delete": {
            "delete": {
                "description": "删除指定 CronJob 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定 CronJob 对象",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cronjob.DeleteCronJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/cronjob/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一 CronJob 对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 CronJob 对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CronJob 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/cronjob/list/{namespace}": {
            "get": {
                "description": "获取某一用户空间下的所有 CronJob 对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一用户空间下的所有 CronJob 对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/deployment/delete": {
            "delete": {
                "description": "删除指定Deployment对象.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定Deployment对象.",
                "parameters": [
                    {
                        "description": "删除一个Deployment对象时所需参数.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deployment.DeleteDeploymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/deployment/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一 Deployment 对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 Deployment 对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/deployment/list/{namespace}": {
            "get": {
                "description": "获取某一用户创建的所有 Deployment 对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一用户创建的所有 Deployment 对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/deployment/pods/{name}/{namespace}": {
            "get": {
                "description": "查询某一 Deployment 对象控制的Pods列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 Deployment 对象控制的Pods列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/job/create": {
            "post": {
                "description": "创建Job对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "创建Job对象",
                "parameters": [
                    {
                        "description": "创建Job对象所需参数.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/job.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/job/delete": {
            "delete": {
                "description": "删除指定Job对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定Job对象",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/job.DeleteJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/job/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一Job对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一Job对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/job/list/{namespace}": {
            "get": {
                "description": "获取某一用户创建的所有Job对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一用户创建的所有Job对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/job/pods/{name}/{namespace}": {
            "get": {
                "description": "查询某一Job对象控制的Pods列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一Job对象控制的Pods列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/persistentvolumeclaim/create": {
            "post": {
                "description": "创建PersistentVolumeClaim对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "创建PersistentVolumeClaim对象",
                "parameters": [
                    {
                        "description": "创建PersistentVolumeClaim对象所需参数.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/persistentvolumeclaim.CreatePersistentVolumeClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/persistentvolumeclaim/delete": {
            "delete": {
                "description": "删除指定的PersistentVolumeClaim对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定的PersistentVolumeClaim对象",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/persistentvolumeclaim.DeletePersistentVolumeClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/persistentvolumeclaim/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一PersistentVolumeClaim对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一PersistentVolumeClaim对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PersistentVolumeClaim对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/persistentvolumeclaim/list/{namespace}": {
            "get": {
                "description": "获取某一用户创建的所有PersistentVolumeClaim对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一用户创建的所有PersistentVolumeClaim对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/pod/container/{podId}/{namespace}": {
            "get": {
                "description": "获取某一 Pod 中的所有容器对象.",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一 Pod 中的所有容器对象.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod ID",
                        "name": "podId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/pod/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一 Pod 对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 Pod 对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/pod/list/{namespace}": {
            "get": {
                "description": "获取某一命名空间下的所有 Pod 对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一命名空间下的所有 Pod 对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/secret/create": {
            "post": {
                "description": "创建 Secret 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "创建 Secret 对象",
                "parameters": [
                    {
                        "description": "创建 Secret 对象时所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/secret.CreateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/secret/delete": {
            "delete": {
                "description": "删除指定Secret对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定Secret对象",
                "parameters": [
                    {
                        "description": "删除参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/secret.DeleteSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/secret/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一 Secret 对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 Secret 对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Secret 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/secret/list/{namespace}": {
            "get": {
                "description": "获取某一命名空间下的所有 Secret 对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一命名空间下的所有 Secret 对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/service/delete": {
            "delete": {
                "description": "删除指定 Service 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "删除指定 Service 对象",
                "parameters": [
                    {
                        "description": "删除 Service 对象时所需的参数.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.DeleteServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/service/detail/{name}/{namespace}": {
            "get": {
                "description": "查询某一 Service 对象的详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 Service 对象的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/service/list/{namespace}": {
            "get": {
                "description": "获取某一用户创建的所有 Service 对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取某一用户创建的所有 Service 对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/service/pods/{name}/{namespace}": {
            "get": {
                "description": "查询某一 Service 对象对应的Pods列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 Service 对象对应的Pods列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户的命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/storageclass/detail/{name}": {
            "get": {
                "description": "查询某一 StorageClass 对象的详情.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "查询某一 StorageClass 对象的详情.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "StorageClass 对象名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200, \"message\":\"OK\", \"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/resource/storageclass/list": {
            "get": {
                "description": "获取某一用户创建的所有Job对象",
                "tags": [
                    "resource"
                ],
                "summary": "获取所有 StorageClass 对象列表.",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "post": {
                "description": "创建 User 对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "创建 User 对象",
                "parameters": [
                    {
                        "description": "创建 User 对象时所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/tool.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ConfigMapArg": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "Items ConfigMap 对象 配置项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.ConfigMapItem"
                    }
                }
            }
        },
        "common.ConfigMapItem": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "Key 配置项的 Key.",
                    "type": "string"
                },
                "value": {
                    "description": "Value 配置项的 Value. 目前只支持base64格式编码的字符串.",
                    "type": "string"
                }
            }
        },
        "common.CustomRootPasswordArg": {
            "type": "object",
            "properties": {
                "value": {
                    "description": "SecretValue",
                    "type": "string"
                }
            }
        },
        "common.DataVolumeArg": {
            "type": "object",
            "properties": {
                "accessModes": {
                    "description": "AccessModes 访问模式",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "capacity": {
                    "description": "Capacity 存储容量",
                    "type": "number"
                },
                "storageClassName": {
                    "description": "StorageClassName 存储类名称",
                    "type": "string"
                }
            }
        },
        "configmap.ConfigMapItem": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "Key 配置项的 Key.",
                    "type": "string"
                },
                "value": {
                    "description": "Value 配置项的 Value. 目前只支持base64格式编码的字符串.",
                    "type": "string"
                }
            }
        },
        "configmap.CreateConfigMapRequest": {
            "type": "object",
            "properties": {
                "item": {
                    "description": "ConfigMapItems 配置项数组.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/configmap.ConfigMapItem"
                    }
                },
                "name": {
                    "description": "Name ConfigMap对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "configmap.DeleteConfigMapRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "ConfigMap 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "cronjob.CreateCronJobRequest": {
            "type": "object",
            "properties": {
                "cronjob": {
                    "type": "object",
                    "$ref": "#/definitions/cronjob.CronJobArgs"
                },
                "name": {
                    "description": "Name CronJob 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "cronjob.CronJobArgs": {
            "type": "object",
            "properties": {
                "jobTemplate": {
                    "type": "object",
                    "$ref": "#/definitions/model.JobArgs"
                },
                "schedule": {
                    "description": "The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.",
                    "type": "string"
                }
            }
        },
        "cronjob.DeleteCronJobRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "CronJob 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "deployment.ConfigVariable": {
            "type": "object",
            "properties": {
                "mountPath": {
                    "description": "MountPath 配置文件挂载路径，代表这个服务如果想要成功运行，需要到那个路径下去获取这个配置文件.",
                    "type": "string"
                },
                "name": {
                    "description": "Name 一个ConfigMap对象的名称，必须是与应用同命名空间下的一个可用ConfigMap对象的名称.",
                    "type": "string"
                },
                "readOnly": {
                    "description": "ReadOnly",
                    "type": "boolean"
                }
            }
        },
        "deployment.DeleteDeploymentRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name Deployment对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "deployment.EnvironmentVariable": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the variable. Must be a C_IDENTIFIER.",
                    "type": "string"
                },
                "value": {
                    "description": "Value of the variable, as defined in Kubernetes core API.",
                    "type": "string"
                }
            }
        },
        "deployment.Label": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "Label key",
                    "type": "string"
                },
                "value": {
                    "description": "Label value",
                    "type": "string"
                }
            }
        },
        "deployment.PersistentVolumeClaimVariable": {
            "type": "object",
            "properties": {
                "mountPath": {
                    "description": "MountPath 持久化存储挂载路径.",
                    "type": "string"
                },
                "name": {
                    "description": "Name 一个 PersistentVolumeClaim 对象的名称，必须是与应用同命名空间下的一个可用 PersistentVolumeClaim 对象的名称.",
                    "type": "string"
                },
                "readOnly": {
                    "description": "ReadOnly",
                    "type": "boolean"
                }
            }
        },
        "job.CreateJobRequest": {
            "type": "object",
            "properties": {
                "jobTemplate": {
                    "description": "Job 对象参数.",
                    "type": "object",
                    "$ref": "#/definitions/model.JobArgs"
                },
                "name": {
                    "description": "Name Job 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "job.DeleteJobRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Job 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "model.JobArgs": {
            "type": "object",
            "properties": {
                "activeDeadlineSeconds": {
                    "description": "Specifies the duration in seconds relative to the startTime that the job may be active\nbefore the system tries to terminate it; value must be positive integer\n+optional",
                    "type": "integer"
                },
                "completions": {
                    "description": "Specifies the desired number of successfully finished pods the\njob should be run with.  Setting to nil means that the success of any\npod signals the success of all pods, and allows parallelism to have any positive\nvalue.  Setting to 1 means that parallelism is limited to 1 and the success of that\npod signals the success of the job.\nMore info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/\n+optional",
                    "type": "integer"
                },
                "parallelism": {
                    "description": "Specifies the maximum desired number of pods the job should\nrun at any given time. The actual number of pods running in steady state will\nbe less than this number when ((.spec.completions - .status.successful) \u003c .spec.parallelism),\ni.e. when the work left to do is less than max parallelism.\nMore info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/\n+optional",
                    "type": "integer"
                },
                "podTemplate": {
                    "description": "PodTemplate 定义了 Job 对象管理的 Pod 对象的定义参数.",
                    "type": "object",
                    "$ref": "#/definitions/model.PodArgs"
                }
            }
        },
        "model.PodArgs": {
            "type": "object",
            "properties": {
                "configmaps": {
                    "description": "List of user-defined configmap variables.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deployment.ConfigVariable"
                    }
                },
                "containerCommand": {
                    "description": "Command that is executed instead of container entrypoint, if specified.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "containerCommandArgs": {
                    "description": "Arguments for the specified container command or container entrypoint (if command is not\nspecified here).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "containerImage": {
                    "description": "Docker image path for the application.",
                    "type": "string"
                },
                "cpuRequirement": {
                    "description": "Optional CPU requirement for the container.",
                    "type": "number"
                },
                "labels": {
                    "description": "Labels that will be defined on Pods/RCs/Services",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deployment.Label"
                    }
                },
                "memoryRequirement": {
                    "description": "Optional memory requirement for the container.",
                    "type": "number"
                },
                "pvcs": {
                    "description": "List of user-defined PersistentVolumeClaim variables.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deployment.PersistentVolumeClaimVariable"
                    }
                },
                "restartPolicy": {
                    "description": "Restart policy for all containers within the pod.\nOne of Always, OnFailure, Never.",
                    "type": "string"
                },
                "variables": {
                    "description": "List of user-defined environment variables.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deployment.EnvironmentVariable"
                    }
                }
            }
        },
        "mysql5.ClusterOptions": {
            "type": "object",
            "properties": {
                "backupvolume": {
                    "description": "BackupVolume 用户自定义备份数据持久化存储参数.",
                    "type": "object",
                    "$ref": "#/definitions/common.DataVolumeArg"
                },
                "clusterId": {
                    "description": "ClusterID Kubernetes 集群ID.",
                    "type": "string"
                },
                "config": {
                    "description": "Config 用户自定义配置文件.",
                    "type": "object",
                    "$ref": "#/definitions/common.ConfigMapArg"
                },
                "datavolume": {
                    "description": "DataVolume 用户定义持久化存储参数.",
                    "type": "object",
                    "$ref": "#/definitions/common.DataVolumeArg"
                },
                "dbName": {
                    "description": "InitDBName 用户初始化数据库名称.",
                    "type": "string"
                },
                "isExport": {
                    "description": "IsExport 是否开放公开服务.",
                    "type": "boolean"
                },
                "members": {
                    "description": "Members MySQL集群节点数.",
                    "type": "integer"
                },
                "name": {
                    "description": "Name MySQL 集群名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                },
                "rootpassword": {
                    "description": "RootPassword 用户自定义root密码.",
                    "type": "object",
                    "$ref": "#/definitions/common.CustomRootPasswordArg"
                }
            }
        },
        "persistentvolumeclaim.CreatePersistentVolumeClaimRequest": {
            "type": "object",
            "properties": {
                "AccessModes": {
                    "description": "AccessModes 存储的访问模式.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "Name PersistentVolumeClaim对象名称",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间",
                    "type": "string"
                },
                "storageCapacity": {
                    "description": "StorageCapacity 申请存储容量.",
                    "type": "number"
                },
                "storageClassName": {
                    "description": "StoraegClassName 存储类名称.",
                    "type": "string"
                }
            }
        },
        "persistentvolumeclaim.DeletePersistentVolumeClaimRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Secret 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "secret.CreateSecretRequest": {
            "type": "object",
            "properties": {
                "item": {
                    "description": "SecretItems Secret 信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/secret.SecretItem"
                    }
                },
                "name": {
                    "description": "Name Secret 对象的名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "secret.DeleteSecretRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name Secret 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间.",
                    "type": "string"
                }
            }
        },
        "secret.SecretItem": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "Key secret item key.",
                    "type": "string"
                },
                "value": {
                    "description": "Value secret item value.",
                    "type": "string"
                }
            }
        },
        "service.DeleteServiceRequest": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "description": "ClusterID Kubernetes 集群ID.",
                    "type": "string"
                },
                "name": {
                    "description": "Name Service 对象名称.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace 命名空间",
                    "type": "string"
                }
            }
        },
        "tool.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.CreateRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
